#!/usr/bin/env bash
# A Bash script that runs infinitely and prints "OK" upon receiving a SIGTERM signal

# Trap SIGTERM signal and display "OK"
trap 'echo "OK"' SIGTERM

# Infinite loop that prints "To infinity and beyond" every 2 seconds
while true
do
  echo "To infinity and beyond"
  sleep 2
done
